services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args: 
        - TURBO_API=${TURBO_API}
        - TURBO_TEAM=${TURBO_TEAM}
      secrets:
        - turbo_token
    restart: always
    ports: [3000:3000]
    networks: [app_network]
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args: 
        - TURBO_API=${TURBO_API}
        - TURBO_TEAM=${TURBO_TEAM}
      secrets:
        - turbo_token
    restart: always
    ports: [3001:3001]
    networks: [app_network]
  react-router-web:
    container_name: react-router-web
    build:
      context: .
      dockerfile: ./apps/react-router-web/Dockerfile
      args:
        - TURBO_API=${TURBO_API}
        - TURBO_TEAM=${TURBO_TEAM}
      secrets:
        - turbo_token
    environment:
      - JAVA_API_HOST=${JAVA_API_HOST}
    restart: always
    ports: [8080:3000]
    networks: [app_network]
  java-api:
    container_name: java-api 
    build:
      context: .
      dockerfile: ./apps/java-api/Dockerfile
      args:
        - TURBO_API=${TURBO_API}
        - TURBO_TEAM=${TURBO_TEAM}
      secrets:
        - turbo_token
    restart: always
    ports: [8081:8080]
    networks: [app_network]

networks:
  app_network:

secrets:
  turbo_token:
    environment: TURBO_TOKEN