services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports: [3000:3000]
    networks: [app_network]
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports: [3001:3001]
    networks: [app_network]
    # command: tail -f /dev/null
  react-router-web:
    container_name: react-router-web
    build:
      context: .
      dockerfile: ./apps/react-router-web/Dockerfile
    restart: always
    ports: [3002:3000]
    networks: [app_network]

networks:
  app_network:
