name: Cleanup Containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write

jobs:
  cleanup:
    name: Cleanup old containers
    runs-on: my-shadcn-app-monorepo
    steps:
      - name: Delete untagged containers
        uses: snok/container-retention-policy@v2
        with:
          image-names: '*'
          cut-off: 1 week ago UTC
          timestamp-to-use: created_at
          account-type: personal
          token: ${{ secrets.PAT }}
          skip-tags: latest, v*
