name: Cleanup Containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read 
  packages: write

jobs:
  cleanup:
    name: Cleanup old containers
    runs-on: my-shadcn-app-monorepo
    steps:
      - name: Delete untagged containers
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: jhs88 
          token: ${{ secrets.PAT }}
          image-names: '*' 
          cut-off: 1h
          timestamp-to-use: created_at
          tag-selection: untagged 