name: Cleanup Containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup:
    name: Cleanup old containers
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged containers
        uses: snok/container-retention-policy@v1
        with:
          image-names: '*'
          cut-off: 1 week ago UTC
          timestamp-to-use: created_at
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-only: true
          skip-tags: latest, v*
