name: Cleanup old container images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  cleanup:
    runs-on: my-shadcn-app-monorepo
    steps:
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List and delete old container images
        run: |
          PACKAGES=$(gh api -H "Accept: application/vnd.github+json" "/repos/${{ github.repository }}/packages?package_type=container" | jq -r '.[].name')
          for pkg in $PACKAGES; do
            echo "Checking package $pkg"
            VERSIONS=$(gh api -H "Accept: application/vnd.github+json" "/repos/${{ github.repository }}/packages/container/$pkg/versions" | jq -r '.[] | select(.metadata.container.tags | length == 0) | .id')
            for version_id in $VERSIONS; do
              echo "Deleting package $pkg version $version_id"
              gh api --method DELETE -H "Accept: application/vnd.github+json" "/repos/${{ github.repository }}/packages/container/$pkg/versions/$version_id"
            done
          done
