name: Supabase Function Tests 
on:
  pull_request:

jobs:
  build:
    runs-on: my-shadcn-app-monorepo
    steps:
      - uses: actions/checkout@v6

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - run: supabase start
      - run: deno test --allow-all deno-test.ts --env-file .env.local
