name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "releases/v*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write

env: # To use Turborepo Remote Caching, set the following environment variables for the job.
  TURBO_TELEMETRY_DISABLED: ${{ vars.TURBO_TELEMETRY_DISABLED }}
  TURBO_API: ${{ vars.TURBO_API }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  build-and-push:
    name: 📦 Build & Deploy Containers
    runs-on: my-shadcn-app-monorepo
    strategy:
      matrix:
        target:
          - next-web:
              - image: next-web
                dockerfile: apps/web/Dockerfile
          - react-router-web:
              - image: react-router-web
                dockerfile: apps/react-router-web/Dockerfile
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login to GHCR 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔧 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.target.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: 🚀 Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.target.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dump:
    runs-on: my-shadcn-app-monorepo
    strategy:
      matrix:
        target:
          - next-web:
              - image: next-web
                dockerfile: apps/web/Dockerfile
          - react-router-web:
              - image: react-router-web
                dockerfile: apps/react-router-web/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
